version: "3.7"
x-thau:
  &thau
  image: mgrin/thau:${GITHUB_SHA:-latest}
  networks:
    - thau-network

services:
  thau-sqlite:
    << : *thau
    image: mgrin/thau:${GITHUB_SHA:-latest}
    environment:
      - ENV=test
      - DATA_BACKEND=sqlite
      - SQLITE_FILENAME=db
      - ENABLED_STRATEGIES=password
    ports:
      - 9001:9000

  thau-mongo:
    << : *thau
    image: mgrin/thau:${GITHUB_SHA:-latest}
    environment:
      - ENV=test
      - DATA_BACKEND=mongo
      - MONGO_URL=mongodb://admin:password@mongo:27017
      - ENABLED_STRATEGIES=password
    ports:
      - 9002:9000
    networks:
      - thau-network

  thau-postgres:
    << : *thau
    image: mgrin/thau:${GITHUB_SHA:-latest}
    environment:
      - ENV=test
      - DATA_BACKEND=postgres
      - PG_HOST=postgres
      - PG_USER=admin
      - PG_PASSWORD=password
      - ENABLED_STRATEGIES=password
    ports:
      - 9003:9000
    command: sh -c "sleep 5 && yarn start"
    networks:
      - thau-network

  thau-sqlite-http:
    << : *thau
    image: mgrin/thau:${GITHUB_SHA:-latest}
    environment:
      - ENV=test
      - DATA_BACKEND=sqlite
      - SQLITE_FILENAME=db
      - ENABLED_STRATEGIES=password
      - EVENTS_BROADCAST_CHANNEL=http
      - BROADCAST_HTTP_URL=http://thau-tests:10000/webhook
    ports:
      - 9004:9000

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - thau-network
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    networks:
      - thau-network

networks:
  thau-network: