version: "3.7"

services:
  thau-sqlite:
    image: mgrin/thau:${GITHUB_SHA:-latest}
    env_file: environments/.env.sqlite
    volumes:
      - ./thau-api:/usr/app:ro
    ports:
      - 9001:9000
    networks:
      - thau-network

  thau-mongo:
    image: mgrin/thau:${GITHUB_SHA:-latest}
    env_file: environments/.env.mongo
    volumes:
      - ./thau-api:/usr/app:ro
    ports:
      - 9002:9000
    networks:
      - thau-network

  thau-postgres:
    image: mgrin/thau:${GITHUB_SHA:-latest}
    env_file: environments/.env.postgres
    volumes:
      - ./thau-api:/usr/app:ro
    ports:
      - 9003:9000
    networks:
      - thau-network

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - thau-network
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    networks:
      - thau-network

networks:
  thau-network: