version: "3.7"
x-thau:
  &thau
  build:
    context: ./thau-api
    target: dev
  volumes:
    - ./thau-api:/usr/app:ro
  networks:
    - thau-network

services:
  thau-sqlite:
    << : *thau
    env_file: environments/.env.sqlite
    ports:
      - 9001:9000

  thau-mongo:
    << : *thau
    env_file: environments/.env.mongo
    ports:
      - 9002:9000
    depends_on:
      - mongo

  thau-postgres:
    << : *thau
    env_file: environments/.env.postgres
    ports:
      - 9003:9000
    depends_on:
      - postgres

  thau-sqlite-http:
    << : *thau
    env_file: environments/.env.sqlite.http
    ports:
      - 9004:9000

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - thau-network
    
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    networks:
      - thau-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  thau-network: