version: "3.7"

services:
  thau-sqlite:
    image: mgrin/thau:latest
    environment:
        - ENV=prod
        - SWAGGER=1
        - DATA_BACKEND=postgres
        - PG_HOST=postgres
        - PG_USER=admin
        - PG_PASSWORD=password
        - ENABLED_STRATEGIES=password,google,facebook
        - GOOGLE_CLIENT_ID=<YOUR_GOOGLE_APP_CLIENT_ID>
        - FACEBOOK_CLIENT_ID=<YOUR_FACEBOOK_APP_CLIENT_ID>
        - FACEBOOK_CLIENT_SECRET=<YOUR_FACEBOOK_APP_CLIENT_SECRET>
        - FACEBOOK_GRAPH_VERSION=v7.0
    ports:
      - 9000:9000
    postgres:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=admin