name: Build, Test and Push Thau API

on:
  push:
    paths:
      - thau-api/**
    branches: [ master ]
  pull_request:
    paths:
      - thau-api/**
      - tests/**
      - .gitthub/workflows/thau-api.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm -g install yarn
      - run: |
          cd thau-api
          yarn
          yarn prettier:check
          yarn lint
          cd ../tests
          yarn
          yarn prettier:check
          yarn lint

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and Test it
      run: |
        echo "BUILDING THE IMAGE"
        cd thau-api
        docker build --target prod --tag mgrin/thau:$GITHUB_SHA .
        cd ../

        echo "BUILDING TESTS IMAGE"
        docker build -t mgrin/thau-tests:$GITHUB_SHA -f tests/Dockerfile tests/

        echo "RUNNING docker-compose.ci"
        docker-compose up -f docker-compose.ci.yaml
        docker-compose ps

        echo "RUNNING TESTS"
        docker run \
          --network=thau_thau-network \
          --env-file ./environments/.env.tests \
          -e "TERM=xterm-256color" \
          thau-tests

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: |
        echo "BUILDING THE IMAGE"
        cd thau-api
        docker build --target prod --tag mgrin/thau:latest .
        docker push mgrin/thau:latest