name: Build, Test and Push Thau API

on:
  push:
    paths:
      - thau-api/**
      - tests/**
      - .github/workflows/thau-api.yml
      - docker-compose.ci.yaml
    branches: [ master ]
  pull_request:
    paths:
      - thau-api/**
      - tests/**
      - .github/workflows/thau-api.yml
      - docker-compose.ci.yaml

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm -g install yarn
      - run: |
          cd thau-api
          yarn
          yarn prettier:check
          yarn lint
          cd ../tests
          yarn
          yarn prettier:check
          yarn lint

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and Test it
      run: |
        echo "BUILDING THE IMAGE"
        cd thau-api
        docker build --target prod --tag mgrin/thau:$GITHUB_SHA .
        cd ../

        echo "RUNNING docker-compose.ci"
        docker-compose -f docker-compose.ci.yaml up -d
        docker-compose -f docker-compose.ci.yaml ps

        echo "BUILDING TESTS IMAGE"
        docker build -t mgrin/thau-tests:$GITHUB_SHA -f tests/Dockerfile tests/

        echo "RUNNING TESTS"
        docker run \
          --network=thau_thau-network \
          -e AUTH_SQLITE_HOST=thau-sqlite:9000 \
          -e AUTH_MONGO_HOST=thau-mongo:9000 \
          -e AUTH_POSTGRES_HOST=thau-postgres:9000 \
          -e ENABLED_STRATEGIES=password \
          -e "TERM=xterm-256color" \
          mgrin/thau-tests:$GITHUB_SHA

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: |
        echo "LOGIN TO DOCKER HUB"
        docker login -u mgrin -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        echo "BUILDING THE IMAGE"
        cd thau-api
        docker build --target prod --tag mgrin/thau:latest .
        docker push mgrin/thau:latest